import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "../globals.css";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      className={`${workSans.variable} antialiased w-full bg-[#0c0c0c] relative min-h-screen`}
    >
      {children}
    </main>
  );
}
